# Generated by Django 4.1.2 on 2022-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_frist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.IntegerField(unique=True),
        ),
    ]
