# Generated by Django 4.1.2 on 2022-12-18 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraccount_created_at_useraccount_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='Description',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='Trust',
            field=models.BooleanField(default=False, verbose_name='مورد اعتماد'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='frist_name',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت فعال بودن حساب'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='مدیر کل بودن'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mail',
            field=models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='postcode',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='province',
            field=models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='اخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.IntegerField(unique=True, verbose_name='شماره موبایل (نام کاربری)'),
        ),
    ]
