# Generated by Django 4.1.5 on 2023-01-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='frist_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='province',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='استان'),
        ),
    ]
