# Generated by Django 4.1.5 on 2023-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useraccount_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='store_image/users_pic/', verbose_name='تصویر کاربر'),
        ),
    ]
