# Generated by Django 4.1.5 on 2023-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useraccount_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شماره تلفن ثابت'),
        ),
    ]
