# Generated by Django 4.1.4 on 2023-05-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useraccount_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rel_userId', to=settings.AUTH_USER_MODEL, verbose_name='آی کاربر')),
            ],
        ),
    ]
