# Generated by Django 4.1.4 on 2023-05-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_trust'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trust',
            options={'verbose_name': 'کاربران مورد اعتماد'},
        ),
    ]
