# Generated by Django 4.1.4 on 2023-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='orders',
            name='frist_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='orders',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نام خانوادگی گیرنده'),
        ),
        migrations.AddField(
            model_name='orders',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AddField(
            model_name='orders',
            name='postcode',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='orders',
            name='province',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='استان'),
        ),
    ]
