# Generated by Django 4.1.4 on 2023-06-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_orders_description_orders_address_orders_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mobile',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شماره موبایل'),
        ),
    ]
