# Generated by Django 4.1.4 on 2023-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_orders_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='des_long',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات تکمیلی'),
        ),
    ]
