# Generated by Django 4.2.5 on 2023-12-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_product_des_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='کد تخفیف')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'عمومی'), (2, 'خصوصی')], verbose_name='نوع کد تخفیف')),
                ('usable', models.IntegerField(verbose_name='دفعات قابل استفاده')),
            ],
        ),
    ]
