# Generated by Django 4.2.5 on 2023-12-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_discounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounts',
            options={'verbose_name': 'کد تخفیف'},
        ),
    ]
