# Generated by Django 4.2.5 on 2023-12-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_discounts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
