# Generated by Django 4.2.5 on 2023-12-31 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_discounts_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='usable',
            field=models.IntegerField(verbose_name='تعداد دفعات قابل استفاده برای هر کاربر'),
        ),
        migrations.CreateModel(
            name='Discounts_used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0, verbose_name='آی دی کاربر')),
                ('used', models.IntegerField(verbose_name='تعداد دفعات استفاده شده')),
                ('discount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_disCode', to='adminpanel.discounts', to_field='code', verbose_name='کد تخفیف')),
            ],
            options={
                'verbose_name': 'کد تخفیف های استفاده شده',
            },
        ),
    ]
