# Generated by Django 4.2.5 on 2023-12-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_discounts_code_alter_discounts_usable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounts',
            name='type',
        ),
        migrations.AddField(
            model_name='discounts',
            name='Discount_type',
            field=models.IntegerField(blank=True, choices=[(1, 'درصدی'), (2, 'مبلغی')], default=0, verbose_name='نوع تخفیف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discounts',
            name='code_type',
            field=models.IntegerField(blank=True, choices=[(1, 'عمومی'), (2, 'خصوصی')], default=0, verbose_name='نوع کد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discounts',
            name='discount',
            field=models.IntegerField(default=10, verbose_name='مقدار تخفیف (درصد/مبلغ)'),
            preserve_default=False,
        ),
    ]
