# Generated by Django 4.2.5 on 2023-12-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_remove_discounts_type_discounts_discount_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounts',
            name='Discount_type',
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount',
            field=models.IntegerField(verbose_name='مقدار تخفیف'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='discount_type',
            field=models.IntegerField(blank=True, choices=[(1, 'درصد'), (2, 'تومان')], default=10, verbose_name='نوع تخفیف'),
            preserve_default=False,
        ),
    ]
