# Generated by Django 4.2.5 on 2024-01-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_remove_discounts_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount_code',
            field=models.CharField(default=100, max_length=50, unique=True, verbose_name='کد تخفیف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='pyable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='مبلغ قابل پرداخت'),
        ),
    ]
