# Generated by Django 4.2.5 on 2024-01-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_orders_discount_code_orders_pyable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount_code',
            field=models.CharField(max_length=50, verbose_name='کد تخفیف'),
        ),
    ]
