# Generated by Django 4.2.5 on 2024-01-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_orders_discount_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pyable',
            new_name='Payable',
        ),
    ]
