# Generated by Django 4.2.5 on 2024-01-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_rename_pyable_orders_payable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Payable',
            new_name='payable',
        ),
    ]
